# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 10:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonyVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AuthenUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uid', models.CharField(max_length=255)),
                ('extra_data', models.TextField(blank=True)),
                ('is_blacklist', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CensorWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('recieved_time', models.DateTimeField(auto_now_add=True)),
                ('last_pub_time', models.DateTimeField(auto_now=True)),
                ('pub_count', models.PositiveIntegerField(default=0)),
                ('is_blacklist', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_app.AuthenUser')),
            ],
        ),
        migrations.CreateModel(
            name='StreamStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(default=datetime.datetime.now)),
                ('realtime_viewer', models.PositiveIntegerField(default=0)),
                ('total_viewer', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='anonyvisitor',
            name='identity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='player_app.AuthenUser'),
        ),
    ]
